- include_vars: set_lin_jumbo_vars.yml 


- name: Get interface IP and MTU size
  set_fact:
    interfaceIP: "{{ element.ipConfig.ip }}"
    interfaceMTU: "{{ element.ipConfig.mtuSize }}"
  loop: "{{ cmsng.networkInterfaces }}"
  vars:
    element: "{{ item }}"
  register: interface_facts


- name: Include-Tasks
  include_tasks: set-jumbo-linux-tasks.yml 
  loop: "{{ interface_facts.results }}"
  loop_control:
    loop_var: lpvr1
  register: interipmtu
